sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '5'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run coverage
  - npm run coveralls
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
